pokemones = [
    {"nombre": "Bulbasaur", "numero": 1, "tipo": ["Planta", "Veneno"], "debilidad": ["Fuego", "Psiquico", "Volador", "Hielo"], "mega_evolucion": False, "gigamax": False},
    {"nombre": "Charmander", "numero": 4, "tipo": ["Fuego"], "debilidad": ["Agua", "Tierra", "Roca"], "mega_evolucion": False, "gigamax": False},
    {"nombre": "Squirtle", "numero": 7, "tipo": ["Agua"], "debilidad": ["Planta", "Electrico"], "mega_evolucion": False, "gigamax": False},
    {"nombre": "Pikachu", "numero": 25, "tipo": ["Electrico"], "debilidad": ["Tierra"], "mega_evolucion": False, "gigamax": True},
    {"nombre": "Jolteon", "numero": 135, "tipo": ["Electrico"], "debilidad": ["Tierra"], "mega_evolucion": False, "gigamax": False},
    {"nombre": "Flareon", "numero": 136, "tipo": ["Fuego"], "debilidad": ["Agua", "Tierra", "Roca"], "mega_evolucion": False, "gigamax": False},
    {"nombre": "Gastly", "numero": 92, "tipo": ["Fantasma", "Veneno"], "debilidad": ["Fantasma", "Psiquico", "Siniestro"], "mega_evolucion": False, "gigamax": False},
    {"nombre": "Haunter", "numero": 93, "tipo": ["Fantasma", "Veneno"], "debilidad": ["Fantasma", "Psiquico", "Siniestro"], "mega_evolucion": False, "gigamax": False},
    {"nombre": "Gengar", "numero": 94, "tipo": ["Fantasma", "Veneno"], "debilidad": ["Fantasma", "Psiquico", "Siniestro"], "mega_evolucion": True, "gigamax": True},
    {"nombre": "Onix", "numero": 95, "tipo": ["Roca", "Tierra"], "debilidad": ["Agua", "Planta", "Hielo", "Lucha", "Acero"], "mega_evolucion": False, "gigamax": False},
    {"nombre": "Voltorb", "numero": 100, "tipo": ["Electrico"], "debilidad": ["Tierra"], "mega_evolucion": False, "gigamax": False},
    {"nombre": "Electrode", "numero": 101, "tipo": ["Electrico"], "debilidad": ["Tierra"], "mega_evolucion": False, "gigamax": False},
    {"nombre": "Magmar", "numero": 126, "tipo": ["Fuego"], "debilidad": ["Agua", "Tierra", "Roca"], "mega_evolucion": False, "gigamax": False},
    {"nombre": "Pinsir", "numero": 127, "tipo": ["Bicho"], "debilidad": ["Fuego", "Volador", "Roca"], "mega_evolucion": True, "gigamax": False},
    {"nombre": "Lapras", "numero": 131, "tipo": ["Agua", "Hielo"], "debilidad": ["Planta", "Electrico", "Lucha", "Roca"], "mega_evolucion": False, "gigamax": True},
    {"nombre": "Ditto", "numero": 132, "tipo": ["Normal"], "debilidad": ["Lucha"], "mega_evolucion": False, "gigamax": False},
    {"nombre": "Aerodactyl", "numero": 142, "tipo": ["Roca", "Volador"], "debilidad": ["Agua", "Electrico", "Hielo", "Acero", "Roca"], "mega_evolucion": True, "gigamax": False},
    {"nombre": "Moltres", "numero": 146, "tipo": ["Fuego", "Volador"], "debilidad": ["Agua", "Electrico", "Roca"], "mega_evolucion": False, "gigamax": False},
    {"nombre": "Mewtwo", "numero": 150, "tipo": ["Psiquico"], "debilidad": ["Fantasma", "Bicho", "Siniestro"], "mega_evolucion": True, "gigamax": False},
    {"nombre": "Mew", "numero": 151, "tipo": ["Psiquico"], "debilidad": ["Fantasma", "Bicho", "Siniestro"], "mega_evolucion": False, "gigamax": False},
    {"nombre": "Cyndaquil", "numero": 155, "tipo": ["Fuego"], "debilidad": ["Agua", "Tierra", "Roca"], "mega_evolucion": False, "gigamax": False},
    {"nombre": "Quilava", "numero": 156, "tipo": ["Fuego"], "debilidad": ["Agua", "Tierra", "Roca"], "mega_evolucion": False, "gigamax": False},
    {"nombre": "Typhlosion", "numero": 157, "tipo": ["Fuego"], "debilidad": ["Agua", "Tierra", "Roca"], "mega_evolucion": False, "gigamax": False},
    {"nombre": "Ampharos", "numero": 181, "tipo": ["Electrico"], "debilidad": ["Tierra"], "mega_evolucion": True, "gigamax": False},
    {"nombre": "Steelix", "numero": 208, "tipo": ["Acero", "Tierra"], "debilidad": ["Fuego", "Agua", "Lucha", "Tierra"], "mega_evolucion": True, "gigamax": False},
    {"nombre": "Scizor", "numero": 212, "tipo": ["Bicho", "Acero"], "debilidad": ["Fuego"], "mega_evolucion": True, "gigamax": False},
    {"nombre": "Heracross", "numero": 214, "tipo": ["Bicho", "Lucha"], "debilidad": ["Fuego", "Volador", "Psiquico", "Hada"], "mega_evolucion": True, "gigamax": False},
    {"nombre": "Houndoom", "numero": 229, "tipo": ["Siniestro", "Fuego"], "debilidad": ["Agua", "Lucha", "Tierra", "Roca"], "mega_evolucion": True, "gigamax": False},
    {"nombre": "Tyranitar", "numero": 248, "tipo": ["Roca", "Siniestro"], "debilidad": ["Agua", "Planta", "Lucha", "Tierra", "Bicho", "Acero", "Hada"], "mega_evolucion": True, "gigamax": False},
    {"nombre": "Sableye", "numero": 302, "tipo": ["Siniestro", "Fantasma"], "debilidad": ["Hada"], "mega_evolucion": True, "gigamax": False},
    {"nombre": "Mawile", "numero": 303, "tipo": ["Acero", "Hada"], "debilidad": ["Fuego", "Tierra"], "mega_evolucion": True, "gigamax": False},
    {"nombre": "Aggron", "numero": 306, "tipo": ["Acero", "Roca"], "debilidad": ["Agua", "Lucha", "Tierra"], "mega_evolucion": True, "gigamax": False},
    {"nombre": "Medicham", "numero": 308, "tipo": ["Lucha", "Psiquico"], "debilidad": ["Volador", "Fantasma", "Hada"], "mega_evolucion": True, "gigamax": False},
    {"nombre": "Manectric", "numero": 310, "tipo": ["Electrico"], "debilidad": ["Tierra"], "mega_evolucion": True, "gigamax": False},
    {"nombre": "Banette", "numero": 354, "tipo": ["Fantasma"], "debilidad": ["Fantasma", "Siniestro"], "mega_evolucion": True, "gigamax": False},
    {"nombre": "Absol", "numero": 359, "tipo": ["Siniestro"], "debilidad": ["Lucha", "Bicho", "Hada"], "mega_evolucion": True, "gigamax": False},
    {"nombre": "Garchomp", "numero": 445, "tipo": ["Dragon", "Tierra"], "debilidad": ["Hielo", "Dragon", "Hada"], "mega_evolucion": True, "gigamax": False},
    {"nombre": "Lucario", "numero": 448, "tipo": ["Lucha", "Acero"], "debilidad": ["Fuego", "Lucha", "Tierra"], "mega_evolucion": True, "gigamax": False},
    {"nombre": "Abomasnow", "numero": 460, "tipo": ["Planta", "Hielo"], "debilidad": ["Fuego", "Lucha", "Volador", "Veneno", "Bicho", "Acero"], "mega_evolucion": True, "gigamax": False},
    {"nombre": "Rotom", "numero": 479, "tipo": ["Electrico", "Fantasma"], "debilidad": ["Fantasma", "Siniestro", "Tierra"], "mega_evolucion": False, "gigamax": False},
    {"nombre": "Lycanroc", "numero": 745, "tipo": ["Roca"], "debilidad": ["Agua", "Planta", "Lucha", "Tierra", "Acero"], "mega_evolucion": False, "gigamax": False},
    {"nombre": "Tyrantrum", "numero": 697, "tipo": ["Roca", "Dragon"], "debilidad": ["Hielo", "Lucha", "Tierra", "Hada", "Acero", "Dragon"], "mega_evolucion": False, "gigamax": False},
    {"nombre": "Aegislash", "numero": 681, "tipo": ["Acero", "Fantasma"], "debilidad": ["Fuego", "Tierra", "Fantasma", "Siniestro"], "mega_evolucion": False, "gigamax": False},
    {"nombre": "Charizard", "numero": 6, "tipo": ["Fuego", "Volador"], "debilidad": ["Agua", "Electrico", "Roca"], "mega_evolucion": True, "gigamax": True},
    {"nombre": "Blastoise", "numero": 9, "tipo": ["Agua"], "debilidad": ["Planta", "Electrico"], "mega_evolucion": True, "gigamax": True},
    {"nombre": "Venusaur", "numero": 3, "tipo": ["Planta", "Veneno"], "debilidad": ["Fuego", "Psiquico", "Volador", "Hielo"], "mega_evolucion": True, "gigamax": True},
    {"nombre": "Butterfree", "numero": 12, "tipo": ["Bicho", "Volador"], "debilidad": ["Fuego", "Volador", "Electrico", "Hielo", "Roca"], "mega_evolucion": False, "gigamax": True},
    {"nombre": "Pikachu Libre", "numero": 25, "tipo": ["Electrico", "Lucha"], "debilidad": ["Tierra", "Psiquico", "Hada"], "mega_evolucion": False, "gigamax": False},
    {"nombre": "Eevee", "numero": 133, "tipo": ["Normal"], "debilidad": ["Lucha"], "mega_evolucion": False, "gigamax": True},
    {"nombre": "Meowth", "numero": 52, "tipo": ["Normal"], "debilidad": ["Lucha"], "mega_evolucion": False, "gigamax": True}
]